spring:
  datasource:
    username: root
    password: HY1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resume

server:
  port: 9090

mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl